baseURL = "https://blog.natsuki-cloud.dev/"
languageCode = 'en-us'
title = "Natsuki's Tech Blog"
theme = 'geekblog'

[params]
  geekblogBackToTop = true
  mainSections = ['posts']

[sitemap]
  changeFreq = 'daily'
  disable = false
  filename = 'sitemap.xml'
  priority = -1

# Output formats for search index
[outputs]
  home = ['HTML', 'RSS', 'JSON']

[outputFormats.JSON]
  mediaType = 'application/json'
  baseName = 'index'
  isPlainText = true

