baseURL = "https://blog.natsuki-cloud.dev/"
languageCode = 'en-us'
title = "Natsuki's Tech Blog"
theme = 'geekblog'

[params]
  geekblogBackToTop = true

[sitemap]
  changeFreq = 'daily'
  disable = false
  filename = 'sitemap.xml'
  priority = -1

